- name: Conexion
  hosts: all
  vars:
  gather_facts: no
  tasks:
    - name: Comprobacion conexion puerto 4440
      ansible.builtin.wait_for:
        host: 192.168.1.228
        port: 444
        state: started
        delay: 0
        timeout: 1
      register: salida_conexion
      ignore_unreachable: true
    - name: resultado
      debug:
        var: salida_conexion

