---
- hosts: localhost
  tasks: 
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: file
        suffix: datos
        path: /playbooks2
      register: tempfile_1

    - name: Visualizar contenido
      ansible.builtin.debug:
        var: tempfile_1

    - name: Use the registered var and the file module to remove the temporary file
      ansible.builtin.file:
        path: "{{ tempfile_1.path }}"
        state: absent
      when: tempfile_1.path is defined


