- name: Conexion
  hosts: all
  vars:
  gather_facts: no
  tasks:
    - name: Comprobacion conexion puerto 4440
      ansible.builtin.git:
        repo: git@github.com:jesushmav/ansible2.git
        dest: /tmp/checkout
        single_branch: yes
        version: main

