- name: Conexion
  hosts: all
  vars:
  gather_facts: no
  tasks:
    - name: Comprobacion conexion puerto 4440
      ansible.builtin.git:
        repo: https://github.dxc.com/Iberia-C-I-AI2Automation/AI2Automation.git
        #repo: https://github.com/jesushmav/ansible2.git
        dest: /tmp/checkout2
        single_branch: yes
        version: main

