- name: Conexion
  hosts: localhost
  vars:
    servidor: rhel8srv1
  gather_facts: no
  tasks:
    - name: "SERVIDOR={{ servidor }}" 
      ansible.builtin.debug:
        msg:
        - SERVIDOR = {{ servidor }}  
          #- servidor=rhel8srv1
          #- incidencia=REQ343536
          #    - name: Visualizar var
          #ansible.builtin.debug:
          #var: servidor
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
