---
- hosts: all
  tasks:
    - name: ver usuario
      shell: |
        /usr/bin/sudo su - jhm 
        /usr/bin/sudo -l
      register: salidasudo
    - name: ver salida
      debug:
        var: salidasudo
